### ISSUE TITLE
200 -> 403 / 401 -> 500 with new Prov API

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/entity-api#106]
Current API is fine:
```
$ curl https://entity.api.hubmapconsortium.org/entities/4e54c868cca02be3a0538b03c1909c3d/provenance
```
New API return 403:
```
$ curl https://entity-api.refactor.hubmapconsortium.org/entities/4e54c868cca02be3a0538b03c1909c3d/provenance
{"error":"403 Forbidden: Not authorized to retrieve provenance data for Entity of id: 4e54c868cca02be3a0538b03c1909c3d"}
```

The follow-up request was 401:
```
$ curl -I https://entity.api.hubmapconsortium.org/entities/dataset/globus-url/4e54c868cca02be3a0538b03c1909c3d
HTTP/1.1 401 Unauthorized
```
Now 500:
```
$ curl https://entity-api.refactor.hubmapconsortium.org/entities/dataset/globus-url/4e54c868cca02be3a0538b03c1909c3d
{"error":"500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application."}
```

**Comment by yuanzhou** [comment]
Thanks for the good examples, I'll look into the access control part of the code.

**Comment by yuanzhou** [comment]
@mccalluc Both issues have been addressed in the refactor version. Deployed on the https://entity-api.refactor.hubmapconsortium.org

Let me know if you find anything else needs to be fixed.

**Comment by yuanzhou** [comment]
@mccalluc @shirey I double checked the two examples and they both have been addressed in the new entity-api. There's one difference I wanted to point out so the portal-ui handles the response correctly:

On the current PROD:
````
$ curl -I https://entity.api.hubmapconsortium.org/entities/dataset/globus-url/4e54c868cca02be3a0538b03c1909c3d
HTTP/1.1 401 Unauthorized
````
The 401 response code is actually not correct when the users send valid globus token but don't have the right permission.

On TEST with new entity-api, we get back 401 with invalid/expired token. 
````
$ curl -I https://entity-api.test.hubmapconsortium.org/entities/dataset/globus-url/4e54c868cca02be3a0538b03c1909c3d
HTTP/1.1 401 Unauthorized
````
And 403 if no token provided or a valid token given but the member doesn't have access to the protected dataset.
````
$ curl -I https://entity-api.test.hubmapconsortium.org/entities/dataset/globus-url/4e54c868cca02be3a0538b03c1909c3d
HTTP/1.1 403 Forbidden
````

@mccalluc for backward combability, the new entity-api still supports `/entities/dataset/globus-url/<id>` URL pattern. In the future, you may use `/dataset/globus-url/<id>`  since `/entities` in the URL for this purpose doesn't really make sense when it only returns the globus URL.
