### ISSUE TITLE
add thumbnail attribute to Sample image uploads

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/entity-api#127]
Add another attribute to uploaded files (at the same level as description)- a boolean called *thumbnail*.

**Comment by jeffechiu** [comment]
All relevant edits are needed to be made in the 'tissueForm.jsx' file.

The backend support comes from the entity-api repository, and the relevant schema is located under 'sample' in the 'entity-api/src/schema/provenance-schema.yaml' file. It connects to ingest-UI through the componentDidMount() function, with the initialize() function creating the 'state' variable for the thumbnail variables to operate in. This is likely working, but still needs to be tested.

Functionality for the thumbnail is written in the onFileChange(), validateThumbnailFile(), handleAddThumbnail(), and handleDeleteThumbnail() functions. Likely that all work properly, except for handleDeleteThumbnail(). All need to be tested.

Functionality for saving the thumbnail in the record is defined in handleSubmit(). All changes made have been cleared due to lack of functionality, and it is better to just start fresh with that function (in regards to thumbnail support, everything else in there is fine). Needs to be written and tested.
