### ISSUE TITLE
404 for all /entities/<lab-uuid>

### ISSUE THREAD

**Issue by mccalluc** [hubmapconsortium/entity-api#16]
There are 6 uuids returned by `/entities/types/lab`:
```
07a29e4c-ed43-11e8-b56a-0e8017bdda58 
308f5ffc-ed43-11e8-b56a-0e8017bdda58 
73bb26e4-ed43-11e8-8f19-0a7c1eab007a 
def5fd76-ed43-11e8-b56a-0e8017bdda58 
03b3d854-ed44-11e8-8bce-0e368f3075e8 
5bd084c8-edc2-11e8-802f-0e368f3075e8
```
but https://entity-api.test.hubmapconsortium.org/entities/07a29e4c-ed43-11e8-b56a-0e8017bdda58 is 404... Am I doing something wrong?

**Comment by cborromeo** [comment]
@mccalluc you are not doing anything wrong.  The "Lab" is a Neo4j construct I made to "complete" the graph.  The Lab represents a node in the Neo4j graph.  All the donors connect to the Lab.  Then, in turn, all the specimens generated from the donors (organs, biopsies, etc.) can be traced back to their Lab.  The Lab is a bit redundant since the provenance_group_uuid and provenance_group_name also provides this information.  The 404 is generated because the Lab is not a fully implemented Neo4j entity like the donors, organs, etc.  

For now, don't try to extract data for the Labs.  They may go away in the future.

**Comment by mccalluc** [comment]
Following up on conversation 1/20: I would like to have it as an invariant that every UUID in the system is resolvable. If you want a new, higher-level issue for that, and close this one, that's fine with me, but I think something should stay open.

**Comment by shirey** [comment]
@mccalluc we'll reopen this, but move to the ready column for a future sprint
