### ISSUE TITLE
Incorrect `group_uuid` assignment to HuBMAP-Protected-Data group

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/entity-api#306]
Po Hu at Children's Hospital of Philadelphia has registered several Samples, Donors, Datasets and Uploads.  It appears as though the Samples that WERE NOT edited (create timestamp doesn't match last modified timestamp) have the incorrect `group_uuid` assigned of `c0a18357-b036-11ea-96d3-0e2053f596b5`, which is the group_uuid for the HuBMAP-Protected-Data group, BUT!- the `group_name` field is correct.

This Neo4j query shows the issue:
```
match (n) where n.created_by_user_email contains 'hup2' and not n.entity_type is null return n.created_by_user_email, n.hubmap_id, n.group_name, n.group_uuid, n.entity_type, n.created_timestamp, n.last_modified_timestamp order by n.group_uuid
```

**Comment by yuanzhou** [comment]
The bug was due to incorrect handling of selected group in ingest UI. @BirdMachine fixed new entity creation across donor/sample/dataset with also adding additional loggings and I've fixed the data in neo4j for Po Hu. Not found same issue for others in eno4j on PROD.

![image](https://user-images.githubusercontent.com/195873/157114262-c4262f97-348a-48b7-b0f1-33fb32b19a06.png)

![image](https://user-images.githubusercontent.com/195873/157114307-e46c87c8-d346-45c7-91cd-adaf45ba84f5.png)
