### ISSUE TITLE
Treat Collections as proper entities

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/entity-api#466]
Currently Collections are not supported with the generic mechanisms via the defined entity types in the [provenance_schema.yaml file](https://github.com/hubmapconsortium/entity-api/blob/main/src/schema/provenance_schema.yaml).  Enable for collections in the following endpoints using the definitions in the provenance_schema.yaml file:
  - `GET /entities/<id>`
  - `GET `/<entity type/entities`
  - `POST `/entities/<entity type>`
  - `PUT `/entities/<id>`

To facilitate PUT and POST methods the transient attribute `dataset_uuids` will need to be added to facilitate passing in the list of dataset uuids that the collection points to.  This should work the same way that the [Dataset.direct_ancestor_uuids](https://github.com/hubmapconsortium/entity-api/blob/2143b4cea47eaa132eeb5699ace02f84e56a45c3/src/schema/provenance_schema.yaml#L279) attribute works.

**Comment by kburke** [comment]
Zhou (Joe) Yuan
  [10:38 AM](https://hubmapconsortium.slack.com/archives/C03A9QJBQ3F/p1683297490700419)
[@Bill Shirey](https://hubmapconsortium.slack.com/team/UE4AZ00SD)
 I was looking at the Collection properties based on Karl's message,

> I'm seeing the indented property names below in Neo4j, and each of them already seems to be covered by a section of the YAML indicated by the non-indented line above it.
> shared_properties
> 	"created_timestamp"
> 	"created_by_user_displayname"
> 	"created_by_user_email"
> 	"created_by_user_sub"
> 	"uuid"
> 	"hubmap_id"
> doi_properties
> 	"registered_doi"
> 	"doi_url"
> 	"creators"
> 	"contacts"
> shared_entity_properties
> 	"last_modified_timestamp"
> 	"last_modified_user_sub"
> 	"last_modified_user_email"
> 	"last_modified_user_displayname"
> 	"entity_type"
> ENTITIES:
>   Collection:	 
> 	"description"
> 	"title"
> So I'm actually think I might not have a lot to do "property-wise"

**Question 1**: One property I found that is not in the list above is data_access_level , some Collection nodes have it while some don't. Do you think we'll need it for Collection? (edited) 
[10:43](https://hubmapconsortium.slack.com/archives/C03A9QJBQ3F/p1683297783656519)
Also, since we've been handling the Collections manually, we add the registered_doi and doi_url when it's published and registered with an DOI.
**Question 2**: should it also need a status property to indicate if it's published or not? Instead of relying on the doi properties.
**Question 3**: depending on how a Collection should be created and updated, we may need another transient property dataset_uuids so we can associate existing datasets to this new collection during creation. And possibly, relink datasets to the existing collection via a PUT call to update? Would this ever happen? We do such for datasets to allow a different list of direct ancestor uuids to be used when updating a dataset, which deletes all the old linkages and rebuilds new ones. (edited) 
New

Bill Shirey
[10:56 AM](https://hubmapconsortium.slack.com/archives/C03A9QJBQ3F/p1683298561191259)
For now data_access_level or status aren't needed, these aren't required for the current task, but may be needed in the future.   We will need a transient property or two like dataset_uuids definitely, and I think I mention that in the issue/card.

**Comment by kburke** [comment]
A list of properties to skip for Collections is in the following:
```
            # Generate trigger data and merge into a big dict
            # and skip some of the properties that are time-consuming to generate via triggers
            properties_to_skip = ['datasets']
```
And for general entities, it is this list:
```
        # We'll return all the properties but skip these time-consuming ones
        # Donor doesn't need to skip any
        # Collection is not handled by this call
        properties_to_skip = [
            # Properties to skip for Sample
            'direct_ancestor',
            # Properties to skip for Upload
            'datasets',
            # Properties to skip for Dataset
            'direct_ancestors',
            'collections',
            'upload',
            'title', 
            'previous_revision_uuid', 
            'next_revision_uuid'
        ]
```
As I understand it from the comments and discussions with Joe, the intent is to skip long-running generated properties.

I'm interested in using the general set for Collections, since it covers '`datasets`'.
But since '`title`' would be in this shared list, I thought I might lose it.  However, it still comes through for a Collection. Tracing it, it seems that it is because the YAML doesn't have `Collection.title.generated=true`

So I think it is all cool to do exactly what I want, except the list content and the name `properties_to_skip` seem to me to kind of obscure this "`generated=true`" criteria.  I know I'm being really picky, but is my analysis right?

Would a `properties_to_skip_if_generated` being more accurate?
