### ISSUE TITLE
Find out why the profiling only captured one trigger method

### ISSUE THREAD

**Issue by yuanzhou** [hubmapconsortium/entity-api#641]
Based on the entity-api [profiling generated](https://github.com/hubmapconsortium/search-api/issues/748#issuecomment-1986383405) result [entity_stats.prof.txt](https://github.com/hubmapconsortium/entity-api/files/14580543/entity_stats.prof.txt) (remove the `.txt` extension to run with SnakeViz), there's only one schema trigger method found. This seems to be very strange when a Publication node is connected to 200 Datasets.

<img width="1290" alt="Screenshot 2024-03-12 at 9 08 10 PM" src="https://github.com/hubmapconsortium/entity-api/assets/195873/71c12b1b-b264-481a-a1c5-6764a1d59555">

Find out why the profiling didn't capture other trigger methods. Hint: no need to reindex, just make a GET call against the Publication node or one of the direct ancestor Dataset node and generate another profiling result to compare.

**Comment by DerekFurstPitt** [comment]
[entity_stats.prof.zip](https://github.com/hubmapconsortium/entity-api/files/14653388/entity_stats.prof.zip)
@yuanzhou This is the run of the profiler in entity that captures a dataset (rather than a sample) so multiple read triggers are run. 

Worth noting, in contrast to profiling an entity api call for a sample, the percentage of time occupied by calling uuid-api's get_hubmap_ids is comparatively low. It only appeared so high in the sample run because, since fewer triggers are run, the generate_triggered_data took up less time, so proportionally, the uuid api call took more time.
